[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
bold.family = "FiraCode Nerd Font"

bold.style = "Bold"
italic.family = "FiraCode Nerd Font"
italic.style = "Italic"
size = 14.0
offset.x = 0

offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

[window]
padding.x = 10
padding.y = 10
dynamic_title = true
decorations = "full"

[scrolling]
history = 10000
multiplier = 3


# Default colors
[colors.primary]
background = '#0c0c0c'
foreground = '#cccccc'

# Normal colors
[colors.normal]

black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#13a10e'
yellow     = '#c19c00'

blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'


# Bright colors
[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'

[colors.cursor]
text = "0x2E3440"
cursor = "0xD8DEE9"

[colors.selection]
text = "0xECEFF4"
background = "0x4C566A"

